"""add_slug_to_newsletter

Revision ID: 1ed7baeaf282
Revises: ce35472309a4
Create Date: 2025-07-24 12:32:05.618379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ed7baeaf282'
down_revision: Union[str, Sequence[str], None] = 'ce35472309a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newsletters', sa.Column('slug', sa.String(), nullable=True))
    op.create_index(op.f('ix_newsletters_slug'), 'newsletters', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_newsletters_slug'), table_name='newsletters')
    op.drop_column('newsletters', 'slug')
    # ### end Alembic commands ###