"""add search_folder to newsletter

Revision ID: 75ed3dbf1e16
Revises: 1ed7baeaf282
Create Date: 2025-08-12 21:13:07.535625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75ed3dbf1e16'
down_revision: Union[str, Sequence[str], None] = '1ed7baeaf282'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newsletters', sa.Column('search_folder', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('newsletters', 'search_folder')
    # ### end Alembic commands ###
